name: Release
# On Released
on:
  release:
    types: [published]
  push:

jobs:
  build-swift:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build Swift Package
        run: swift build -c release
      - name: Archive Swift Package
        run: python3 package.py --ext=dylib --folder=.build/release
      - name: Upload Swift Package
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
